#!/bin/sh

# check for pulseaudio group or add one
getent group pulse || /usr/sbin/groupadd pulse
getent group pulse-access || /usr/sbin/groupadd pulse-access

# check for pulseaudio user or add one
getent passwd pulse || /usr/sbin/useradd -g pulse -d /var/run/pulse -s /bin/false -c "Pulseaudio User" pulse

# lock the account
/usr/bin/passwd -l pulse
